
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 11 16:47:49 EEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 50;
  public static final int FUNCTION = 9;
  public static final int GREATER_OR_EQUAL = 38;
  public static final int RIGHT_BRACKET = 18;
  public static final int UMINUS = 31;
  public static final int MINUS_MINUS = 33;
  public static final int NOT_EQUAL = 36;
  public static final int GREATER = 34;
  public static final int CONTINUE = 8;
  public static final int LESS = 35;
  public static final int FOR = 3;
  public static final int MINUS = 30;
  public static final int REAL_LITERAL = 49;
  public static final int NOT = 42;
  public static final int SEMICOLON = 15;
  public static final int CMP_EQUAL = 39;
  public static final int QUASI_CLOSE = 46;
  public static final int LESS_OR_EQUAL = 37;
  public static final int NIL = 12;
  public static final int COMMA = 23;
  public static final int LOGIC_AND = 40;
  public static final int QUASI_ESC = 43;
  public static final int DOUBLE_DOT = 22;
  public static final int DIV = 27;
  public static final int RIGHT_PARENTHESIS = 14;
  public static final int OPEN_BLOCK = 19;
  public static final int PLUS = 29;
  public static final int ASSIGN = 25;
  public static final int IF = 4;
  public static final int ID = 47;
  public static final int DOT = 21;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int PLUS_PLUS = 32;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int MOD = 28;
  public static final int BREAK = 7;
  public static final int LOGIC_OR = 41;
  public static final int COLON = 16;
  public static final int ELSE = 5;
  public static final int CLOSE_BLOCK = 20;
  public static final int DOUBLE_COLON = 24;
  public static final int WHILE = 2;
  public static final int QUASI_OPEN = 45;
  public static final int FALSE = 11;
  public static final int QUASI_EXEC = 44;
  public static final int LEFT_BRACKET = 17;
  public static final int LEFT_PARENTHESIS = 13;
  public static final int INTEGER_LITERAL = 48;
}

